services:
  dashboard: 
    image: linuxserver/heimdall:latest
    container_name: cat_dashboard
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes: 
      - ./config/heimdall:/config
    ports:
      - 8080:80
    restart: unless-stopped
  monitor:
    image: louislam/uptime-kuma
    container_name: uptime_kuma
    volumes: 
      - ./config/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped 
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD:
       ''
    volumes: 
       - './etc-pihole:/etc/pihole'
       - './etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
         - "53:53/tcp"
         - "53:53/udp"
         - "8081:80/tcp" 
